name: rclone

on:
  workflow_dispatch:

jobs:
  BaiduPCS-115:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
                
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          
      # 使用 Rclone 上传文件
        run: 'rclone sync e3-s: google: --progress'

