name: Rclone Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行

  push:
    branches:
      - main  # 触发条件：推送到 main 分支时运行

jobs:
  rclone-job:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      # 检出代码仓库
      - name: Checkout code
        uses: actions/checkout@v3

      # 安装 Rclone
      - name: Setup Rclone
        uses: actionshub/setup-rclone@v2
        with:
          rclone-version: stable  # 最新稳定版

      # 配置 Rclone
      - name: Configure Rclone
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}  # 使用 GitHub Secret
        run: |
          echo "$RCLONE_CONFIG" | base64 -d > ~/.config/rclone/rclone.conf
          rclone listremotes

      # 使用 Rclone 上传文件
      - name: Upload files to remote
        run: |
          rclone sync e3-s: google: --progress
